preload = ~/.config/backgrounds/double-bubble-dark.webp
preload = ~/.config/backgrounds/tcdr-0262_waifu2x_noise0_scale4x.png
preload = ~/.config/backgrounds/wallhaven-k7qjv1.jpg
wallpaper = DP-1,~/.config/backgrounds/wallhaven-k7qjv1.jpg
wallpaper = HDMI-A-2,~/.config/backgrounds/wallhaven-k7qjv1.jpg
